framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    
    handle_all_throwables: true
    enabled_locales: ['en', 'fr']

    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
    php_errors:
        log: true

    property_info:
        enabled: false
        with_constructor_extractor: false

when@dev:
    framework:
        test: true

when@test:
    framework:
        test: true
