framework:
    rate_limiter:
        write_api:
            policy: sliding_window
            limit: 60
            interval: '1 minute'

when@test:
    framework:
        rate_limiter:
            write_api:
                policy: sliding_window
                limit: 10000
                interval: '1 minute'
