networks:
  pokenini-local:
    external: true

services:
  php:
    networks:
      default:
        aliases:
          - back-php
      pokenini-local: {}
  web:
    networks:
      default: {}
      pokenini-local:
        aliases:
          - back.pokenini.local
