services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $apiUrl: '%env(API_URL)%'
            string $apiCafilePath: '%env(API_CAFILE_PATH)%'
            string $listAdmin: '%env(LIST_ADMIN)%'
            string $listTrainer: '%env(LIST_TRAINER)%'
            string $listCollector: '%env(LIST_COLLECTOR)%'
            bool $isInvitationRequired: '%env(bool:REQUIRE_INVITATION)%'
            string $apiLogin: '%env(API_LOGIN)%'
            string $apiPassword: '%env(API_PASSWORD)%'
            string $githubImagesWorkflowToken: '%env(GITHUB_IMAGES_WORKFLOW_TOKEN)%'
            string $githubImagesRepo: '%env(GITHUB_IMAGES_REPO)%'
            string $githubImagesWorkflowFile: '%env(GITHUB_IMAGES_WORKFLOW_FILE)%'
            string $githubImagesWorkflowBFile: '%env(GITHUB_IMAGES_WORKFLOW_B_FILE)%'
            string $githubResourcesRepo: '%env(GITHUB_RESOURCES_REPO)%'
            int $topCount: '%env(ELECTION_TOP_COUNT)%'
            int $electionCandidateCount: '%env(ELECTION_CANDIDATE_COUNT)%'
            string $env: '%kernel.environment%'
            string $metadataDir: '%kernel.project_dir%/resources/metadata'
            string $sessionTokenSecret: '%env(SESSION_TOKEN_SECRET)%'
            int $sessionTtl: '%env(int:SESSION_TTL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Api\GithubActionsApiService $bannerGithubActionsApiService:
        class: App\Service\Api\GithubActionsApiService
        arguments:
            $githubImagesWorkflowFile: '%env(GITHUB_BANNERS_WORKFLOW_FILE)%'

