name: Composer (main) install
description: Install from the main composer
author: Renaud Douze
runs:
  using: "composite"
  steps:
    - name: Prepare
      uses: ./.github/actions/local-php

    - name: Cache composer dependencies
      uses: actions/cache@v4
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}

    - name: Run composer install
      shell: bash
      run: composer install --no-interaction --prefer-dist
